# Generated by Django 2.2.10 on 2020-03-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200229_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='uapuser',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
