# Generated by Django 2.2.10 on 2020-03-04 21:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_uapuser_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='uapuser',
            name='bio',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
