# Generated by Django 3.0.3 on 2020-04-15 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_uapuser_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uapuser',
            name='email',
        ),
    ]
