# Generated by Django 2.2.10 on 2020-03-03 17:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urp',
            old_name='contactant',
            new_name='posted_by',
        ),
        migrations.AlterField(
            model_name='urp',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
