# Generated by Django 2.2.10 on 2020-03-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200304_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('AP', 'Applying'), ('AC', 'Accepted'), ('RE', 'Rejected'), ('CA', 'Canceled')], default='AP', max_length=2),
        ),
    ]
