# Generated by Django 3.0.3 on 2020-04-13 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_application_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
